name: Laravel

on: [pull_request, push]
    
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Copy .env
      run: |
        php -r "file_exists('.env') || copy('.env.testing', '.env');"
        echo AIRPORT_API_KEY=${{ secrets.AIRPORT_API_KEY }} >> .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Generate key
      run: php artisan key:generate --env=testing
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
            DB_CONNECTION: sqlite
            DB_DATABASE: database/database.sqlite
      run: |
        php artisan migrate --seed
        vendor/bin/phpunit
    - name: Show Laravel Log
      if: ${{ failure() }}
      run: cat storage/logs/laravel*.log
